"""
Production FastAPI prediction and model serving application.
"""
import os
from datetime import datetime
from typing import Dict, Any, List, Optional
import joblib
import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware

from .schemas import (
    HealthResponse,
    ModelInfoResponse,
    MetricsResponse,
    SinglePredictionRequest,
    SinglePredictionResponse,
    BatchPredictionRequest,
    BatchPredictionResponse,
    FeatureSchemaItem,
)

app = FastAPI(
    title="Autonomous Data Scientist Prediction API",
    description="High-performance serving endpoint for models generated by Autonomous Data Scientist.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

MODEL_BUNDLE_PATH = os.environ.get("MODEL_BUNDLE_PATH", "artifacts/model_bundle.joblib")
_bundle: Optional[Dict[str, Any]] = None
_bundle_mtime: float = 0.0


def get_model_bundle(force_reload: bool = False) -> Dict[str, Any]:
    global _bundle, _bundle_mtime
    if not os.path.exists(MODEL_BUNDLE_PATH):
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"No trained model registered at '{MODEL_BUNDLE_PATH}'. Run the pipeline first."
        )
    current_mtime = os.path.getmtime(MODEL_BUNDLE_PATH)
    if _bundle is None or force_reload or current_mtime > _bundle_mtime:
        try:
            _bundle = joblib.load(MODEL_BUNDLE_PATH)
            _bundle_mtime = current_mtime
        except Exception as e:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"Failed to load model bundle: {str(e)}"
            )
    return _bundle


@app.post("/model/reload", tags=["Model"])
def reload_model():
    """Forces reloading of the model bundle from disk."""
    bundle = get_model_bundle(force_reload=True)
    return {
        "status": "reloaded",
        "model_name": bundle.get("best_model_name"),
        "target_column": bundle.get("target_column"),
        "created_at": bundle.get("created_at"),
    }


@app.get("/health", response_model=HealthResponse, tags=["System"])
def health_check():
    """Checks API availability and loaded model status."""
    is_loaded = False
    model_name = None
    try:
        bundle = get_model_bundle()
        is_loaded = True
        model_name = bundle.get("best_model_name")
    except HTTPException:
        pass

    return HealthResponse(
        status="healthy",
        model_loaded=is_loaded,
        model_name=model_name,
        timestamp=datetime.now().isoformat(),
    )


def _sanitize_val(v: Any) -> Any:
    if isinstance(v, (np.integer, np.int64, np.int32)):
        return int(v)
    if isinstance(v, (np.floating, np.float64, np.float32)):
        return float(v)
    if isinstance(v, (np.ndarray, list)):
        return [_sanitize_val(x) for x in v]
    if pd.isna(v):
        return None
    return str(v) if not isinstance(v, (int, float, bool)) else v


@app.get("/model", response_model=ModelInfoResponse, tags=["Model"])
def get_model_info():
    """Returns registered model metadata, problem type, and input feature schema."""
    bundle = get_model_bundle()
    schema_items = [
        FeatureSchemaItem(
            name=f["name"],
            dtype=f["dtype"],
            sample_value=_sanitize_val(f.get("sample_value")),
            is_numerical=f.get("is_numerical", True),
            unique_values=[_sanitize_val(v) for v in f.get("unique_values")] if f.get("unique_values") else None,
        )
        for f in bundle.get("feature_schema", [])
    ]
    return ModelInfoResponse(
        status="success",
        best_model_name=bundle.get("best_model_name", "Unknown"),
        best_model_id=bundle.get("best_model_id", "unknown"),
        problem_type=bundle.get("problem_spec").problem_type.value,
        target_column=bundle.get("target_column", "target"),
        primary_metric=bundle.get("primary_metric", "metric"),
        best_score=float(bundle.get("best_score", 0.0)),
        baseline_score=float(bundle.get("baseline_score", 0.0)),
        feature_schema=schema_items,
        created_at=bundle.get("created_at", ""),
    )


@app.get("/metrics", response_model=MetricsResponse, tags=["Model"])
def get_metrics():
    """Returns optimization scores and best hyperparameter values."""
    bundle = get_model_bundle()
    return MetricsResponse(
        status="success",
        primary_metric=bundle.get("primary_metric", "metric"),
        best_score=float(bundle.get("best_score", 0.0)),
        baseline_score=float(bundle.get("baseline_score", 0.0)),
        best_params=bundle.get("best_params", {}),
        problem_type=bundle.get("problem_spec").problem_type.value,
    )


@app.post("/predict", response_model=SinglePredictionResponse, tags=["Inference"])
def predict_single(req: SinglePredictionRequest):
    """Executes single record inference through the full trained pipeline."""
    bundle = get_model_bundle()
    pipeline = bundle["pipeline"]
    problem_spec = bundle["problem_spec"]

    # Convert single feature dict to 1-row DataFrame
    input_df = pd.DataFrame([req.features])

    try:
        raw_pred = pipeline.predict(input_df)[0]
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"Inference error with provided features: {str(e)}"
        )

    prob = None
    probs_dict = None

    if problem_spec.is_classification and hasattr(pipeline, "predict_proba"):
        try:
            proba_arr = pipeline.predict_proba(input_df)[0]
            if len(proba_arr) == 2:
                prob = float(proba_arr[1])
            else:
                prob = float(np.max(proba_arr))

            if bundle.get("classes") and len(bundle["classes"]) == len(proba_arr):
                probs_dict = {
                    str(cls_name): float(p)
                    for cls_name, p in zip(bundle["classes"], proba_arr)
                }
        except Exception:
            pass

    # Map numeric prediction back to class name if classes are available
    final_pred = raw_pred
    if problem_spec.is_classification and bundle.get("classes"):
        try:
            cls_idx = int(raw_pred)
            if 0 <= cls_idx < len(bundle["classes"]):
                final_pred = bundle["classes"][cls_idx]
        except (ValueError, TypeError):
            pass

    if isinstance(final_pred, (np.integer, np.floating)):
        final_pred = final_pred.item()

    return SinglePredictionResponse(
        status="success",
        prediction=final_pred,
        probability=prob,
        probabilities=probs_dict,
        problem_type=problem_spec.problem_type.value,
    )


@app.post("/predict/batch", response_model=BatchPredictionResponse, tags=["Inference"])
def predict_batch(req: BatchPredictionRequest):
    """Executes batch inference on a list of input records."""
    if not req.records:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Records list is empty."
        )

    bundle = get_model_bundle()
    pipeline = bundle["pipeline"]
    problem_spec = bundle["problem_spec"]

    input_df = pd.DataFrame(req.records)

    try:
        raw_preds = pipeline.predict(input_df)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"Batch inference failed: {str(e)}"
        )

    probs = None
    if problem_spec.is_classification and hasattr(pipeline, "predict_proba"):
        try:
            prob_arr = pipeline.predict_proba(input_df)
            if prob_arr.shape[1] == 2:
                probs = [float(p[1]) for p in prob_arr]
            else:
                probs = [float(np.max(p)) for p in prob_arr]
        except Exception:
            probs = None

    # Map back to classes if classification
    final_preds = []
    for p in raw_preds:
        mapped = p
        if problem_spec.is_classification and bundle.get("classes"):
            try:
                idx = int(p)
                if 0 <= idx < len(bundle["classes"]):
                    mapped = bundle["classes"][idx]
            except (ValueError, TypeError):
                pass
        if isinstance(mapped, (np.integer, np.floating)):
            mapped = mapped.item()
        final_preds.append(mapped)

    return BatchPredictionResponse(
        status="success",
        count=len(final_preds),
        predictions=final_preds,
        probabilities=probs,
    )
